#!/usr/bin/env python3
"""Generate the production mixed-FP16 ADA300 LUT header from abc_lut JSON."""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import subprocess
from pathlib import Path


TABLES = {
    "exponential": ("exponential_exp2_fp32_lut.json", "exp2", "[0,1) exp2 core"),
    "sin": ("sin_halfpi_fp32_lut.json", "sin", "[0,pi/2] shared sin core"),
    "reciprocal": ("reciprocal_normalized_fp32_lut.json", "reciprocal", "[1,2) normalized core"),
    "rsqrt": ("rsqrt_normalized_fp32_lut.json", "rsqrt", "[1,2) normalized core"),
    "sqrt": ("sqrt_normalized_fp32_lut.json", "sqrt", "[1,2) normalized core"),
    "log": ("log_normalized_fp32_lut.json", "log", "[1,2) normalized core"),
}

SEGMENT_LAYOUTS = {
    16: {
        "output_dir": "ada300_bxc_16segments",
        "runner": "lut_fp/test_ada300_bxc_16seg.py",
    },
    31: {
        "output_dir": "ada300_bxc_31segments",
        "runner": "lut_fp/test_ada300_bxc_31seg.py",
    },
    63: {
        "output_dir": "ada300_bxc_63segments",
        "runner": "lut_fp/test_ada300_bxc_63seg.py",
    },
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def f32(value: float) -> float:
    return struct.unpack("<f", struct.pack("<f", value))[0]


def f32_hex(value: float) -> str:
    return f"{f32(value).hex()}f"


def effective_f32_range_max(value: float) -> float:
    """Largest FP32 value accepted by the runner's range_float upper bound."""
    candidate = f32(value)
    if candidate <= value:
        return candidate
    bits = struct.unpack("<I", struct.pack("<f", candidate))[0]
    return struct.unpack("<f", struct.pack("<I", bits - 1))[0]


def git_value(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(root), *args], text=True).strip()


def load_table(path: Path, json_key: str, *, num_segments: int) -> tuple[list[float], list[float], list[float], list[float]]:
    payload = json.loads(path.read_text())[json_key]
    if payload["num_segments"] != num_segments or len(payload["segments"]) != num_segments:
        raise ValueError(f"{path}: expected exactly {num_segments} segments")

    thresholds = []
    compare_max = []
    slopes = []
    offsets = []
    for index, segment in enumerate(payload["segments"]):
        if segment["segment_id"] != index:
            raise ValueError(f"{path}: non-contiguous segment id at {index}")
        thresholds.append(f32(segment["threshold_quantized"][1]))
        compare_max.append(effective_f32_range_max(segment["range_float"][1]))
        coefficients = segment.get("coefficients_fp32")
        if coefficients is None:
            coefficients = segment["coefficients_float"]
        slopes.append(f32(coefficients["b"]))
        offsets.append(f32(coefficients["c"]))
    return thresholds, compare_max, slopes, offsets


def load_layout(abc_root: Path, num_segments: int) -> tuple[dict, dict]:
    layout = SEGMENT_LAYOUTS[num_segments]
    json_root = abc_root / "lut_fp/output" / layout["output_dir"]
    runner = abc_root / layout["runner"]
    tables = {}
    sources = {}
    for name, (filename, json_key, semantics) in TABLES.items():
        path = json_root / filename
        tables[name] = load_table(path, json_key, num_segments=num_segments)
        sources[name] = {
            "path": str(path.relative_to(abc_root)),
            "sha256": sha256(path),
            "segments": num_segments,
            "semantics": semantics,
        }
    return tables, {
        "output_dir": layout["output_dir"],
        "runner": {"path": str(runner.relative_to(abc_root)), "sha256": sha256(runner)},
        "tables": sources,
    }


def render_array(symbol: str, values: list[float]) -> str:
    body = "\n".join(f"    {f32_hex(value)}," for value in values)
    return f"static const float {symbol}[GGML_LUT_NUM_SEGMENTS_REEX] = {{\n{body}\n}};\n"


def render_table_block(tables: dict, sources: dict) -> list[str]:
    lines: list[str] = []
    for name, (_, _, semantics) in TABLES.items():
        thresholds, compare_max, slopes, offsets = tables[name]
        lines.append(f"/* {name}: {semantics}; JSON sha256={sources[name]['sha256']} */")
        lines.append(render_array(f"ggml_reex_{name}_fp32_threshold", thresholds).rstrip())
        lines.append(render_array(f"ggml_reex_{name}_fp32_compare_max", compare_max).rstrip())
        lines.append(render_array(f"ggml_reex_{name}_fp32_b", slopes).rstrip())
        lines.append(render_array(f"ggml_reex_{name}_fp32_c", offsets).rstrip())
        lines.append("")
    return lines


def render_header(layout_tables: dict[int, dict], layout_sources: dict[int, dict]) -> str:
    lines = [
        "/* Auto-generated by tests/test-reex/generate_ada300_lut_header.py. Do not edit. */",
        "/* Embeds 16-, 31-, and 63-segment mixed-FP16 FP32 tables; GGML_LUT_NUM_SEGMENTS_REEX selects branch. */",
        "#ifndef GGML_REEX_LUT_DATA_H",
        "#define GGML_REEX_LUT_DATA_H",
        "",
        "#ifdef GGML_USE_REEX",
        '#include "ggml-reex-lut-config.h"',
        "",
    ]
    segment_values = sorted(SEGMENT_LAYOUTS)
    for index, num_segments in enumerate(segment_values):
        if index == 0:
            lines.append(f"#if GGML_LUT_NUM_SEGMENTS_REEX == {num_segments}")
        else:
            lines.append(f"#elif GGML_LUT_NUM_SEGMENTS_REEX == {num_segments}")
        lines.append(
            f"/* Source: abc_lut/lut_fp/output/{SEGMENT_LAYOUTS[num_segments]['output_dir']} */"
        )
        lines.extend(render_table_block(layout_tables[num_segments], layout_sources[num_segments]["tables"]))
    lines.extend(
        [
            "#else",
            '#error "GGML_LUT_NUM_SEGMENTS_REEX must be 16, 31, or 63"',
            "#endif",
            "",
            "#endif /* GGML_USE_REEX */",
            "",
            "#endif /* GGML_REEX_LUT_DATA_H */",
            "",
        ]
    )
    return "\n".join(lines)


def build_manifest(
    abc_root: Path,
    header_path: Path,
    header_hash: str,
    layout_meta: dict[int, dict],
) -> dict:
    return {
        "schema": "ada300-pwnl-lut-data-v1",
        "abc_lut": {
            "commit": git_value(abc_root, "rev-parse", "HEAD"),
            "dirty": bool(git_value(abc_root, "status", "--porcelain")),
        },
        "default_segments": 16,
        "supported_segments": sorted(SEGMENT_LAYOUTS),
        "precision": "mixed_fp16",
        "segment_compare": "effective FP32 upper bound derived from range_float",
        "layouts": {str(num_segments): layout_meta[num_segments] for num_segments in sorted(SEGMENT_LAYOUTS)},
        "header": {"path": str(header_path.resolve()), "sha256": header_hash},
    }


def main() -> None:
    script = Path(__file__).resolve()
    repo = script.parents[2]
    parser = argparse.ArgumentParser()
    parser.add_argument("--abc-lut-root", type=Path, default=script.parents[4] / "abc_lut")
    parser.add_argument("--header", type=Path, default=repo / "ggml/include/reex/ggml-reex-lut-data.h")
    parser.add_argument("--manifest", type=Path, default=repo / "ggml/include/reex/ggml-reex-lut-data.manifest.json")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    abc_root = args.abc_lut_root.resolve()
    layout_tables: dict[int, dict] = {}
    layout_meta: dict[int, dict] = {}
    for num_segments in sorted(SEGMENT_LAYOUTS):
        tables, meta = load_layout(abc_root, num_segments)
        layout_tables[num_segments] = tables
        layout_meta[num_segments] = meta

    header_text = render_header(layout_tables, layout_meta)
    header_hash = hashlib.sha256(header_text.encode()).hexdigest()
    manifest = build_manifest(abc_root, args.header, header_hash, layout_meta)
    manifest_text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"

    if args.check:
        if not args.header.exists() or args.header.read_text() != header_text:
            raise SystemExit(f"generated header differs: {args.header}")
        if not args.manifest.exists() or args.manifest.read_text() != manifest_text:
            raise SystemExit(f"generated manifest differs: {args.manifest}")
        print(f"PASS header={header_hash}")
        return

    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(header_text)
    args.manifest.write_text(manifest_text)
    print(f"wrote {args.header} sha256={header_hash}")
    print(f"wrote {args.manifest}")


if __name__ == "__main__":
    main()
