// SPDX-License-Identifier: MIT
//
// reex_turboquant_wht.h — REEX_TURBOQUANT only.
//
// CPU implementation of the structured fast Walsh-Hadamard rotation used by
// `GGML_OP_REEX_WHT`:
//
//     forward(x) = (1/sqrt(d)) * Diag(s2) * H_d * Diag(s1) * x
//     inverse(y) = (1/sqrt(d)) * Diag(s1) * H_d * Diag(s2) * y
//
// where H_d is the unscaled d×d Sylvester-Hadamard matrix (so H_d * H_d = d·I)
// and s1/s2 ∈ {-1,+1}^d are the deterministic sign tables generated by
// `tools/reex/reex_turboquant_gen_wht_signs.cpp` (PRNG seed=42).  Because
// `H_d` is symmetric and self-inverse up to scale, the (s1, butterfly, s2,
// norm) and (s2, butterfly, s1, norm) compositions are exact inverses of each
// other; this is what `reex_turboquant_cpu_wht_forward / _inverse` rely on.
//
// The runtime per-channel `scale_inv` (the InnerQ rescaling described in
// docs/turboquant/01_设计与实现计划.md §3.3) is *not* baked into the sign
// tables — callers pass it as an optional buffer and the kernel multiplies
// the input row pointwise BEFORE the rotation.  Phase 1 only exercises the
// no-scale path (`scale_inv == NULL`); the scaled path lands with the
// InnerQ wiring in P4 A2.4 (Stage 2 onwards).
//
// The optional `sq_accum` buffer (Phase 4 / P4 A2.4 Stage 2a) lets InnerQ
// accumulate per-channel post-WHT variance during the calibration window
// without a second graph node — the same op handles both calibration
// (`sq_accum != NULL`, `scale_inv == NULL`) and steady-state
// (`sq_accum == NULL`, `scale_inv != NULL`).
//
// Only `d == 128` and `d == 64` are supported in Phase 1 (matching the only
// head_dim values currently in `block_tq_k3`).  Other dimensions abort with a
// clear error so silent wrong-result paths are impossible.
//
// All entry points live in this header; the `_signs.inc` table itself is
// inlined into the only TU that defines them
// (`reex_turboquant_wht.c`) so other backends pulling sign data must do so
// through their own copy of the `.inc`.

#pragma once

#ifdef REEX_TURBOQUANT

#include "ggml.h"

#ifdef __cplusplus
extern "C" {
#endif

// `direction`:
//   0 = forward   (s1 → butterfly → s2)
//   1 = inverse   (s2 → butterfly → s1)
//
// `scale_inv`: optional per-channel multiplier of length `dim`, applied
//   **BEFORE** the rotation:
//
//       y = (1/sqrt(d)) * Diag(s_outer) * H_d * Diag(s_inner) * (x ⊙ scale_inv)
//
//   This pre-rotation placement is required by InnerQ EMA's invariance:
//   `<Q ⊙ scale_inv, K ⊙ scale> == <Q, K>` only holds when the per-channel
//   reweighting is applied to the input vectors before any orthogonal
//   transform.  WHT is orthogonal and inner-product-preserving, but it is
//   NOT diagonal, so post-rotation scaling does not commute with the dot
//   product.  Pass NULL to skip the pre-multiplication entirely (Phase 1
//   parity behaviour).
//
// `sq_accum`: optional per-channel accumulator of length `dim` (F64 ABI for
//   numerical headroom; written in serial inside this row).  When non-NULL,
//   each element of the rotated output is squared and added in-place:
//
//       sq_accum[i] += y[i] * y[i]   (post-normalisation, per channel)
//
//   This drives InnerQ EMA's "calibrate-then-freeze" phase where the caller
//   accumulates per-channel variance of post-WHT keys before deciding the
//   equalisation scale.  Pass NULL to skip.
//
// `scale_inv` and `sq_accum` are independent — both, either, or neither may
// be non-NULL.  When both are non-NULL the accumulator sees the
// post-equalisation rotated output, which is rarely useful but legal.
//
// Operates on a single contiguous row of length `dim`.  In-place safe
// (`x == out` is allowed).
GGML_API void reex_turboquant_cpu_wht_apply_row(
        const float *  GGML_RESTRICT x,
        float       *  GGML_RESTRICT out,
        int64_t                       dim,
        int                           direction,
        const float *  GGML_RESTRICT scale_inv,
        double      *                sq_accum);

// Convenience: applies WHT row-by-row to a (rows, dim) F32 matrix.  Used by
// the GGML_OP_REEX_WHT compute path; tests can call it directly to avoid
// going through ggml_compute_forward.
//
// `sq_accum` is shared across all rows (each row contributes additively).
// The caller is responsible for thread-safety; the GGML_OP_REEX_WHT
// dispatcher pins this op to a single thread when sq_accum is non-NULL.
GGML_API void reex_turboquant_cpu_wht_apply_rows(
        const float *  GGML_RESTRICT x,
        float       *  GGML_RESTRICT out,
        int64_t                       rows,
        int64_t                       dim,
        int                           direction,
        const float *  GGML_RESTRICT scale_inv,
        double      *                sq_accum);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // REEX_TURBOQUANT
