// SPDX-License-Identifier: MIT
//
// reex_turboquant_gen_constants_v_polar
//
// Offline generator that dumps TurboQuant V-β (P4 A2.5) codebook constants
// to a header-only `.inc` file consumed by the production CPU / CUDA
// kernels for GGML_TYPE_TQ_V_POLAR2 / TQ_V_POLAR4.
//
// V-β path (TheTom turbo2_0 / turbo4_0 aligned): the V cache is rotated
// via V WHT (same group=128 op as K cache, applied in graph layer
// src/llama-kv-cache.cpp::cpy_v + src/llama-graph.cpp::build_attn_mha),
// then PolarQuant scalar quantization with Lloyd-Max codebook (4 centroids
// @ 2-bit / 16 centroids @ 4-bit, both for dim=128 N(0,1)-marginal under
// WHT-induced gaussianization) plus norm correction (‖dequant‖ ≡ ‖x‖).
//
// Re-run after any change to the oracle algorithm
// (tests/oracle/reex_turboquant_oracle_core.cpp); the generated `.inc`
// is committed alongside the source so production builds never re-compute
// them.
//
// Usage:
//   reex_turboquant_gen_constants_v_polar <out.inc>
//
// Generated symbols (all `static const` at file scope):
//   reex_turboquant_codebook_tq_v_polar2_centroids[4]
//   reex_turboquant_codebook_tq_v_polar2_decision_boundaries[3]
//   reex_turboquant_codebook_tq_v_polar4_centroids[16]
//   reex_turboquant_codebook_tq_v_polar4_decision_boundaries[15]
//
// Related files:
//   - docs/turboquant/p4.a25_v_polar_design.md §3.4 / §5
//   - ggml/src/ggml-common.h::block_tq_v_polar2 / block_tq_v_polar4
//   - ggml/src/reex_turboquant_quants_ref.c

#include "reex_turboquant_oracle_core.h"

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

namespace tq = reex_turboquant_oracle;

namespace {

constexpr int32_t V_DIM           = 128;     // QK_TQ_V_POLAR2 == QK_TQ_V_POLAR4
constexpr int32_t V_POLAR2_BITS   = 2;       // 4 centroids
constexpr int32_t V_POLAR4_BITS   = 4;       // 16 centroids

void emit_array(FILE * f, const char * name, const std::vector<float> & v, int per_line = 4) {
    std::fprintf(f, "static const float %s[%zu] = {", name, v.size());
    for (size_t i = 0; i < v.size(); ++i) {
        if ((static_cast<int>(i) % per_line) == 0) {
            std::fprintf(f, "\n   ");
        }
        std::fprintf(f, " %.10ff,", v[i]);
    }
    std::fprintf(f, "\n};\n\n");
}

bool emit_codebook(FILE * f, int32_t dim, int32_t bits, const char * suffix) {
    tq::Codebook cb = tq::reex_turboquant_oracle_codebook_get(dim, bits);
    if (static_cast<int>(cb.centroids.size()) != (1 << bits) ||
        static_cast<int>(cb.decision_boundaries.size()) != (1 << bits) - 1) {
        std::fprintf(stderr,
            "unexpected codebook shape for bits=%d: centroids=%zu, decision_boundaries=%zu\n",
            bits, cb.centroids.size(), cb.decision_boundaries.size());
        return false;
    }
    std::fprintf(f, "// %d centroids (%d-bit PolarQuant) for the dim=%d Lloyd-Max codebook.\n",
                 1 << bits, bits, dim);
    char buf[128];
    std::snprintf(buf, sizeof buf, "reex_turboquant_codebook_tq_v_polar%s_centroids", suffix);
    emit_array(f, buf, cb.centroids);

    std::fprintf(f, "// %d decision boundaries (centroid midpoints; lower_bound on this array gives the index).\n",
                 (1 << bits) - 1);
    std::snprintf(buf, sizeof buf, "reex_turboquant_codebook_tq_v_polar%s_decision_boundaries", suffix);
    emit_array(f, buf, cb.decision_boundaries);

    std::fprintf(stderr,
        "  v_polar%s: centroids[%zu], decision_boundaries[%zu]\n",
        suffix, cb.centroids.size(), cb.decision_boundaries.size());
    return true;
}

}  // namespace

int main(int argc, char ** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <out.inc>\n", argv[0]);
        return 1;
    }
    const char * out_path = argv[1];

    FILE * f = std::fopen(out_path, "w");
    if (!f) {
        std::perror("fopen");
        return 1;
    }

    std::fprintf(f, "// SPDX-License-Identifier: MIT\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// reex_turboquant_codebook_tq_v_polar.inc\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// AUTO-GENERATED by tools/reex/reex_turboquant_gen_constants_v_polar.\n");
    std::fprintf(f, "// DO NOT EDIT BY HAND.\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// Re-run the generator after any change to the algorithm oracle\n");
    std::fprintf(f, "// (tests/oracle/reex_turboquant_oracle_core.cpp).\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// Source for GGML_TYPE_TQ_V_POLAR2 / TQ_V_POLAR4 (P4 A2.5 V-β,\n");
    std::fprintf(f, "// 2026-05-11+; TheTom turbo2_0 / turbo4_0 algorithmic alignment):\n");
    std::fprintf(f, "//   build_lloyd_max_codebook(dim=%d, bits=2)  → 4 centroids,\n",  V_DIM);
    std::fprintf(f, "//                                                3 decision boundaries.\n");
    std::fprintf(f, "//   build_lloyd_max_codebook(dim=%d, bits=4)  → 16 centroids,\n", V_DIM);
    std::fprintf(f, "//                                                15 decision boundaries.\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// V-β codebook intent: N(0,1)-marginal under WHT-induced gaussianization\n");
    std::fprintf(f, "// (V WHT applied in graph layer cpy_v; same group=128 op as K WHT).\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// See docs/turboquant/p4.a25_v_polar_design.md §3 / §5 for the full\n");
    std::fprintf(f, "// design spec and TheTom bit-level alignment statement.\n");
    std::fprintf(f, "\n");
    std::fprintf(f, "#ifndef REEX_TURBOQUANT_CODEBOOK_TQ_V_POLAR_INC\n");
    std::fprintf(f, "#define REEX_TURBOQUANT_CODEBOOK_TQ_V_POLAR_INC\n\n");

    if (!emit_codebook(f, V_DIM, V_POLAR2_BITS, "2")) {
        std::fclose(f);
        return 1;
    }
    if (!emit_codebook(f, V_DIM, V_POLAR4_BITS, "4")) {
        std::fclose(f);
        return 1;
    }

    std::fprintf(f, "#endif  // REEX_TURBOQUANT_CODEBOOK_TQ_V_POLAR_INC\n");
    std::fclose(f);

    std::fprintf(stderr, "wrote %s\n", out_path);
    return 0;
}
