// SPDX-License-Identifier: MIT
//
// reex_turboquant_gen_constants
//
// Offline generator that dumps TurboQuant codebook + scaling constants to a
// header-only `.inc` file consumed by the production CPU / CUDA kernels.
//
// Re-run after any change to the oracle algorithm; the generated `.inc` is
// committed alongside the source so production builds never re-compute them
// (and are independent of std::map / std::mutex / Lloyd-Max iteration).
//
// Usage:
//   reex_turboquant_gen_constants <out.inc>
//
// Output for the GGML_TYPE_TQ_K3 production path (P4 A2.2 K3 P3 upgrade,
// TheTom turbo3_0 path: 3-bit full PolarQuant with norm correction, no QJL):
//
//   - K_BITS         = 3   (overall per-element budget for TQ_K3 = full
//                            PolarQuant centroid index, no QJL split)
//   - MSE_BITS       = 3   (Lloyd-Max codebook bits;  2^3 = 8 centroids)
//   - QJL_SIGN_BITS  = 0   (no QJL projection in TheTom path; the on-disk
//                            `signs[]` byte stream now packs the high 1 bit of
//                            the 3-bit centroid index, see 02 §2 / docs/
//                            turboquant/p4.a22_k3_p3_upgrade_plan.md §0)
//
// Generated symbols (all `static const` at file scope):
//   reex_turboquant_codebook_tq_k3_centroids[8]
//   reex_turboquant_codebook_tq_k3_decision_boundaries[7]
//   REEX_TURBOQUANT_QJL_SCALE_TQ_K3   (kept for backward link compatibility;
//                                       no longer referenced by P3 dequant
//                                       path — see plan doc §0.5 #1)

#include "reex_turboquant_oracle_core.h"

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

namespace tq = reex_turboquant_oracle;

namespace {

constexpr int32_t K_DIM        = 128;     // QK_TQ_K3
constexpr int32_t K_BITS       = 3;       // TheTom turbo3_0: full 3-bit PolarQuant
constexpr int32_t MSE_BITS     = 3;       // = K_BITS in TheTom path (no QJL split)

void emit_array(FILE * f, const char * name, const std::vector<float> & v, int per_line = 4) {
    std::fprintf(f, "static const float %s[%zu] = {", name, v.size());
    for (size_t i = 0; i < v.size(); ++i) {
        if ((static_cast<int>(i) % per_line) == 0) {
            std::fprintf(f, "\n   ");
        }
        std::fprintf(f, " %.10ff,", v[i]);
    }
    std::fprintf(f, "\n};\n\n");
}

}  // namespace

int main(int argc, char ** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <out.inc>\n", argv[0]);
        return 1;
    }
    const char * out_path = argv[1];

    tq::Codebook cb = tq::reex_turboquant_oracle_codebook_get(K_DIM, MSE_BITS);

    if (static_cast<int>(cb.centroids.size()) != (1 << MSE_BITS) ||
        static_cast<int>(cb.decision_boundaries.size()) != (1 << MSE_BITS) - 1) {
        std::fprintf(stderr,
            "unexpected codebook shape: centroids=%zu, decision_boundaries=%zu\n",
            cb.centroids.size(), cb.decision_boundaries.size());
        return 1;
    }

    const float qjl_scale  = std::sqrt(static_cast<float>(M_PI) / 2.0f) /
                             static_cast<float>(K_DIM);

    FILE * f = std::fopen(out_path, "w");
    if (!f) {
        std::perror("fopen");
        return 1;
    }

    std::fprintf(f, "// SPDX-License-Identifier: MIT\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// reex_turboquant_codebook_tq_k3.inc\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// AUTO-GENERATED by tools/reex/reex_turboquant_gen_constants.\n");
    std::fprintf(f, "// DO NOT EDIT BY HAND.\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// Re-run the generator after any change to the algorithm oracle\n");
    std::fprintf(f, "// (tests/oracle/reex_turboquant_oracle_core.cpp).\n");
    std::fprintf(f, "//\n");
    std::fprintf(f, "// Source for GGML_TYPE_TQ_K3 (P4 A2.2 K3 P3 upgrade, TheTom turbo3_0\n");
    std::fprintf(f, "// path: K_BITS=%d full PolarQuant + norm correction; no QJL split):\n",
                 K_BITS);
    std::fprintf(f, "//   build_lloyd_max_codebook(dim=%d, bits=%d)  → 8 centroids,\n",
                 K_DIM, MSE_BITS);
    std::fprintf(f, "//                                                 7 decision boundaries.\n");
    std::fprintf(f, "//   QJL_SCALE : sqrt(pi/2) / %d  (legacy emit, kept for backward link\n",
                 K_DIM);
    std::fprintf(f, "//                                  compatibility — no longer referenced\n");
    std::fprintf(f, "//                                  by P3 dequant path; see\n");
    std::fprintf(f, "//                                  docs/turboquant/p4.a22_k3_p3_upgrade_plan.md §0)\n");
    std::fprintf(f, "\n");
    std::fprintf(f, "#ifndef REEX_TURBOQUANT_CODEBOOK_TQ_K3_INC\n");
    std::fprintf(f, "#define REEX_TURBOQUANT_CODEBOOK_TQ_K3_INC\n\n");

    std::fprintf(f, "// %d centroids (K_BITS=%d, full 3-bit PolarQuant) for the dim=%d Lloyd-Max codebook.\n",
                 1 << MSE_BITS, MSE_BITS, K_DIM);
    emit_array(f, "reex_turboquant_codebook_tq_k3_centroids", cb.centroids);

    std::fprintf(f, "// %d decision boundaries (centroid midpoints; lower_bound on this array gives the index).\n",
                 (1 << MSE_BITS) - 1);
    emit_array(f, "reex_turboquant_codebook_tq_k3_decision_boundaries", cb.decision_boundaries);

    std::fprintf(f, "// QJL scale = sqrt(pi/2) / dim_K.  Legacy constant from the P1 simplification\n");
    std::fprintf(f, "// (see plan doc §0.5 #1); no longer referenced by P3 dequant path but kept\n");
    std::fprintf(f, "// at file scope so legacy `(void)REEX_TURBOQUANT_QJL_SCALE_TQ_K3` references\n");
    std::fprintf(f, "// continue to link until they are scrubbed in §6.13 doc-sync follow-up.\n");
    std::fprintf(f, "static const float REEX_TURBOQUANT_QJL_SCALE_TQ_K3 = %.10ff;\n\n", qjl_scale);

    std::fprintf(f, "#endif  // REEX_TURBOQUANT_CODEBOOK_TQ_K3_INC\n");
    std::fclose(f);

    std::fprintf(stderr, "wrote %s\n", out_path);
    std::fprintf(stderr, "  centroids[%zu], decision_boundaries[%zu]\n",
                 cb.centroids.size(), cb.decision_boundaries.size());
    std::fprintf(stderr, "  QJL_SCALE  = %.10f (legacy)\n", qjl_scale);
    return 0;
}
