// SPDX-License-Identifier: MIT
//
// reex_turboquant_gen_wht_signs — REEX_TURBOQUANT only.
//
// Offline tool. Emits the deterministic ±1 sign tables that parameterise the
// fast Walsh-Hadamard rotation used by `GGML_OP_REEX_WHT`:
//
//     y = (1 / sqrt(d)) · Diag(s2) · H_d · Diag(s1) · x
//
// where H_d is the unscaled d×d Sylvester-Hadamard matrix and s1/s2 ∈ {-1,+1}^d
// are layer-independent random sign vectors.  The "(s1, butterfly, s2, norm)"
// structure matches docs/turboquant/01_设计与实现计划.md §1.3 and §6 (P1.3 WHT
// 算子) and the layer-independent variant in §3.3 (the per-layer InnerQ scale
// is *not* baked into the signs — it is fed as a separate runtime tensor).
//
// Determinism contract
// --------------------
// We use std::mt19937 (the same PRNG family the oracle picks) with a global
// base seed of 42 (default `LayerConfig::seed`).  Each (dim, position) pair
// claims its own sub-stream by offsetting the seed:
//
//     stream(s1, d128) = 42 + 0
//     stream(s2, d128) = 42 + 1
//     stream(s1, d64 ) = 42 + 2
//     stream(s2, d64 ) = 42 + 3
//
// When this layout is changed, the regenerated `.inc` MUST be committed and
// every cos_sim ≥ 0.999 fixture under tests/reex/ MUST be re-baselined.  See
// docs/turboquant/04_naming_and_isolation.md.
//
// Usage
// -----
//     reex_turboquant_gen_wht_signs            # → ggml/src/ggml-cpu/reex/reex_turboquant_wht_signs.inc
//     reex_turboquant_gen_wht_signs -o /tmp/foo.inc
//
// The generated file is a self-contained C header fragment intended to be
// `#include`d by the CPU WHT kernel TU; it has no external dependencies.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <random>
#include <sstream>
#include <string>
#include <vector>

namespace {

constexpr int32_t  BASE_SEED  = 42;
constexpr uint32_t STREAM_S1_D128 = 0;
constexpr uint32_t STREAM_S2_D128 = 1;
constexpr uint32_t STREAM_S1_D64  = 2;
constexpr uint32_t STREAM_S2_D64  = 3;

std::vector<int8_t> draw_signs(int32_t dim, uint32_t stream) {
    std::mt19937 rng(static_cast<uint32_t>(BASE_SEED) + stream);
    std::uniform_int_distribution<uint32_t> bit(0, 1);
    std::vector<int8_t> out(static_cast<size_t>(dim));
    for (int32_t i = 0; i < dim; ++i) {
        out[static_cast<size_t>(i)] = bit(rng) ? +1 : -1;
    }
    return out;
}

void emit_array(std::ostream & os, const char * name, const std::vector<int8_t> & v, int per_row = 16) {
    os << "static const int8_t " << name << "[" << v.size() << "] = {";
    for (size_t i = 0; i < v.size(); ++i) {
        if ((i % per_row) == 0) {
            os << "\n    ";
        }
        os << (v[i] >= 0 ? "+1" : "-1");
        if (i + 1 < v.size()) os << ", ";
    }
    os << "\n};\n";
}

void emit_header(std::ostream & os) {
    os <<
        "// AUTO-GENERATED by tools/reex/reex_turboquant_gen_wht_signs.\n"
        "// Do NOT edit by hand: any change here MUST go through the generator\n"
        "// and bumps every cos_sim >= 0.999 fixture in tests/reex/.\n"
        "//\n"
        "// Source-of-truth: tools/reex/reex_turboquant_gen_wht_signs.cpp\n"
        "//   base seed         = 42 (== LayerConfig::seed in tests/oracle/)\n"
        "//   sub-stream offsets: s1_d128=0, s2_d128=1, s1_d64=2, s2_d64=3\n"
        "//   PRNG              : std::mt19937 (uniform 0..1, mapped to {-1,+1})\n"
        "//\n"
        "// These tables encode the fast Walsh-Hadamard rotation\n"
        "//     y = (1/sqrt(d)) * Diag(s2) * H_d * Diag(s1) * x\n"
        "// used by reex_turboquant_cpu_wht_forward/_inverse.\n"
        "//\n"
        "// Scope: REEX_TURBOQUANT only.\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <stdint.h>\n"
        "\n";
}

}  // namespace

int main(int argc, char ** argv) {
    std::string out_path;
    for (int i = 1; i < argc; ++i) {
        const std::string a = argv[i];
        if ((a == "-o" || a == "--output") && i + 1 < argc) {
            out_path = argv[++i];
        } else if (a == "-h" || a == "--help") {
            std::cout
                << "usage: reex_turboquant_gen_wht_signs [-o OUT.inc]\n"
                   "  -o, --output   path to .inc file (default: stdout)\n";
            return 0;
        } else {
            std::cerr << "unknown arg: " << a << "\n";
            return 2;
        }
    }

    std::ostringstream buf;
    emit_header(buf);

    const auto s1_d128 = draw_signs(128, STREAM_S1_D128);
    const auto s2_d128 = draw_signs(128, STREAM_S2_D128);
    const auto s1_d64  = draw_signs(64,  STREAM_S1_D64);
    const auto s2_d64  = draw_signs(64,  STREAM_S2_D64);

    emit_array(buf, "reex_turboquant_wht_signs_s1_d128", s1_d128);
    buf << "\n";
    emit_array(buf, "reex_turboquant_wht_signs_s2_d128", s2_d128);
    buf << "\n";
    emit_array(buf, "reex_turboquant_wht_signs_s1_d64",  s1_d64);
    buf << "\n";
    emit_array(buf, "reex_turboquant_wht_signs_s2_d64",  s2_d64);

    if (out_path.empty()) {
        std::cout << buf.str();
        return 0;
    }

    std::ofstream f(out_path, std::ios::binary | std::ios::trunc);
    if (!f) {
        std::cerr << "ERROR: cannot open " << out_path << " for writing\n";
        return 1;
    }
    f << buf.str();
    if (!f) {
        std::cerr << "ERROR: write failed: " << out_path << "\n";
        return 1;
    }
    std::cout << "wrote " << out_path << " ("
              << s1_d128.size() << "+" << s2_d128.size() << "+"
              << s1_d64.size()  << "+" << s2_d64.size()  << " ±1 entries)\n";
    return 0;
}
